✔ |  OK F W S | Context

⠏ |   0       | tests
⠋ |   1       | tests
✔ |   1       | tests

⠏ |   0       | Expectations
⠋ |   1       | Expectations
⠙ |   1 1     | Expectations
⠹ |   1 2     | Expectations
⠸ |   1 3     | Expectations
⠼ |   1 4     | Expectations
⠴ |   2 4     | Expectations
✖ |   2 4     | Expectations
────────────────────────────────────────────────────────────────────────────────
tests.R:12: failure: Failure:1
Failure has been forced

tests.R:16: failure: Failure:2a
Failure has been forced

tests.R:19: failure: Failure:2b
FALSE isn't true.

tests.R:24: failure: Failure:loop
`i` not equal to 2.
1/1 mismatches
[1] 1 - 2 == -1
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | Expectations2
✔ |   0       | Expectations2

⠏ |   0       | Errors
⠋ |   0 1     | Errors
⠙ |   0 2     | Errors
✖ |   0 2     | Errors
────────────────────────────────────────────────────────────────────────────────
tests.R:33: error: Error:1
stop
Backtrace:
 1. NULL
 2. base::eval(code, test_env)

tests.R:47: error: Error:3
!
Backtrace:
 1. f()
 2. g()
 3. h()
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | Recursion
⠋ |   0 1     | Recursion
✖ |   0 1     | Recursion
────────────────────────────────────────────────────────────────────────────────
tests.R:56: error: Recursion:1
This is deep
Backtrace:
  1. f(25)
  2. f(x - 1)
  3. f(x - 1)
  4. f(x - 1)
  5. f(x - 1)
  6. f(x - 1)
  7. f(x - 1)
  8. f(x - 1)
  9. f(x - 1)
 10. f(x - 1)
 11. f(x - 1)
 12. f(x - 1)
 13. f(x - 1)
 14. f(x - 1)
 15. f(x - 1)
 16. f(x - 1)
 17. f(x - 1)
 18. f(x - 1)
 19. f(x - 1)
 20. f(x - 1)
 21. f(x - 1)
 22. f(x - 1)
 23. f(x - 1)
 24. f(x - 1)
 25. f(x - 1)
 26. f(x - 1)
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | Skips
⠋ |   0     1 | Skips
⠙ |   0     2 | Skips
⠹ |   0     3 | Skips
✔ |   0     3 | Skips
────────────────────────────────────────────────────────────────────────────────
tests.R:62: skip: Skip:1
Reason: skip

tests.R:69: skip: Skip:2
Reason: skip

tests.R:72: skip: Skip:3
Reason: empty test
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | Warnings
⠋ |   0   1   | Warnings
⠙ |   0   2   | Warnings
⠹ |   0   3   | Warnings
✔ |   0   3   | Warnings
────────────────────────────────────────────────────────────────────────────────
tests.R:78: warning: Warning:1
abc

tests.R:84: warning: Warning:2
def

tests.R:85: warning: Warning:2
ghi
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | Output
⠋ |   1       | Output
⠙ |   2       | Output
✔ |   2       | Output

⠏ |   0       | Backtraces
⠋ |   0 1     | Backtraces
⠙ |   0 2     | Backtraces
⠹ |   0 3     | Backtraces
⠸ |   0 4     | Backtraces
✖ |   0 4     | Backtraces
────────────────────────────────────────────────────────────────────────────────
tests.R:99: error: errors thrown at block level are entraced
foo
Backtrace:
 1. f()
 2. g()

tests.R:104: error: errors thrown from a quasi-labelled argument are entraced
foo
Backtrace:
 1. testthat::expect_is(foo(), "foo")
 4. foo()

tests.R:111: error: errors thrown from a quasi-labelled argument are entraced (deep case)
foo
Backtrace:
 1. testthat::expect_is(f(), "foo")
 4. f()
 5. g()
 9. foo()

tests.R:121: error: errors thrown from a quasi-labelled argument are entraced (deep deep case)
foobar
Backtrace:
 1. f()
 2. g()
 6. foo()
 7. bar()
────────────────────────────────────────────────────────────────────────────────

⠏ |   0       | End
✔ |   0       | End

══ Terminating early ═══════════════════════════════════════════════════════════
Too many failures
